version: '3'
services:
  react-app:
    image: "node:alpine"
    working_dir: /home/node/app 
    ports:
      - "80:3000"
      - "5000:5000"
    volumes:
      - .:/home/node/app
    command: ["yarn","start"]
    networks:
      static-network:
        ipv4_address: 172.18.0.2
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.18.0.0/16
        
